### ISSUE TITLE
PEP 8 Changes ToDo

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#448]
Besides #435 there are much more changes necessary to be mostly [PEP 8](https://peps.python.org/pep-0008/) compliant.

This should be a kind of ToDo and space to discuss this. Especially to find an appropriate time. I generally agree with @tsteinruecken['s opinion](https://github.com/viur-framework/viur-core/pull/435#pullrequestreview-978546720) to do this all at once, but not necessarily now.

- [ ]  Make all class names `CapitalizedWords`
  - [x] #435
- [ ] Make variable and method names `lower_case_with_underscores`
- [ ] Rename arguments, variables and attribute names which are python keywords
  - [ ]  [...Bone.type](https://github.com/viur-framework/viur-core/blob/develop/src/viur/core/bones/numeric.py#L35-L36)
  - [ ] [NumericBone.min/max](https://github.com/viur-framework/viur-core/blob/bb407494b385d25525e87e90dffa2b6e1becb4c9/core/bones/numericBone.py#L20-L21)
  - [ ] `bytes` in `core.render.html.env.viur.fileSize`
  - [ ] `type` in `viur.core.render.html.default.Render.copySuccess`
- [ ] Reduce line length (tbh 79 is sometimes really short, but lines like [this](https://github.com/viur-framework/viur-core/blob/bb407494b385d25525e87e90dffa2b6e1becb4c9/core/render/html/env/viur.py#L686) are definitely too long.)
- [x] Use spaces (#470)
- [ ] Replace `assert` statements with proper exceptions/conditions or use them only sparingly for internal checks/assumptions. Described in https://github.com/viur-framework/viur-core/pull/507#discussion_r970617891
- [ ] Create a ViUR style guide to define rules which aren't strict regulated in the PEP-8 or deviate.
- [x] Enforce the style by a linter with GitHub-Actions or git-hooks
- [ ] Replace sth. like `if len(kwargs) == 0:` with `if not kwargs:`

Feel free to edit this list above.
